### ISSUE TITLE
输出的结果 没有导出功能

### ISSUE THREAD

**Issue by mlb0925** [Linxfeng/flow-eda#3]
输出的结果 没有导出功能 比如excel 或者存在数据库表里

**Comment by Linxfeng** [comment]
- 输出的结果，是可以由您自由处理的，比如可以在输出节点后面使用mysql节点将数据插入到数据库中。
- 输出的结果在节点属性栏里，是提供了一键复制的功能的，您可以复制出去使用
- 至于导出为Excel功能，这个后期会考虑出一个文件类的一类节点，例如保存文件节点，但是由于本项目的运行引擎在后端运行，所以文件生成之后需要用户再下载到本地，这块功能我会规划到v2.3.0版本来实现

**Comment by Linxfeng** [comment]
- 输出的结果，是可以由您自由处理的，比如可以在输出节点后面使用mysql节点将数据插入到数据库中
- 输出的结果在节点属性栏里，是提供了一键复制的功能的，您可以复制出去使用
- 至于导出为Excel功能，由于本项目的运行引擎在后端运行，与前端的文件交互有些不适应，所以暂不考虑文件读写相关功能
