### ISSUE TITLE
能否告知Node、npm的版本呢

### ISSUE THREAD

**Issue by dreambyday** [Linxfeng/flow-eda#7]

**Comment by Linxfeng** [comment]
这个我没测过，应该是兼容大多数常用版本的，这里我说一下我本地开发环境：node  v14.18.0, npm  v7.13.0.

**Comment by dreambyday** [comment]
感谢~我进行了如下操作
npm install yarn -g
yarn add @rollup/plugin-alias
并且注释掉index.html中的<%= htmlWebpackPlugin.options.title %>
加上您的环境（18和16也试过可以）
能够正常打包了

**Comment by Linxfeng** [comment]
好的，感谢您对项目的支持~
我没有进行额外的操作，仅仅只是将项目clone到本地，然后按照文档里写的执行 npm install 就可以正常使用。
所以没有遇到您这种问题。
