### ISSUE TITLE
能否扩展一个节点：将多条支路汇总起来，然后运算的节点

### ISSUE THREAD

**Issue by wang974278863** [Linxfeng/flow-eda#9]
比如有两个支路：支路1和支路2。扩展的节点功能为：将支路1和支路2的值进行加法运算然后输出。   非常感谢

**Comment by Linxfeng** [comment]
好的，安排！
根据你的需求结合本项目的整体结构，可以使用拼接节点，将多条支路的结果的值进行连接。
对于加法运算，我打算设计一个运算节点，支持对任意两个值进行加减乘除等简单运算并输出结果。
